logging:
  level:
    org:
      springframework:
        web:
          INFO
      hibernate:
        ERROR
    com:
      dogigiri:
        petclinic:
          DEBUG


spring:
  # i18internationalization
  messages:
    basename: messages/messages
  # Profiles
  profiles:
    active: "springdatajpa"
#    active: "mapservice"

