logging:
  level:
    org:
      springframework:
        web:
          INFO
      hibernate:
        ERROR
    com:
      dogigiri:
        petclinic:
          DEBUG

# i18internationalization
spring:
  messages:
    basename: messages/messages

